insert into PERMISSIONS (IS_ENABLED, NAME)
values (true, 'CREATE_USER');

insert into PERMISSIONS (IS_ENABLED, NAME)
values (true, 'UPDATE_USER');

SELECT * FROM PERMISSIONS;

INSERT INTO ROLES (IS_ENABLED, NAME) VALUES (true, 'ADMIN');
INSERT INTO ROLES (IS_ENABLED, NAME) VALUES (true, 'USER');

select * from ROLES;

insert into ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) values (1, 1);
insert into ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) values (1, 2);
