openapi: 3.0.4
info:
  title: Inventory API
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /auth/sign-in:
    post:
      summary: Sign in
      operationId: signIn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Successful sign in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'

  /users/create:
    post:
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '200':
          description: Successful user creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        '404':
          description: Resource not found. In this case, the possible causes is that the role id does not exist in the database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResponse'

components:
  schemas:
    SignInRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: "test@example.com"
        password: "password"
    SignInResponse:
      type: object
      properties:
        token:
          type: string
      example:
        token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
    NewUserRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        roleId:
          type: integer
        email:
          type: string
        password:
          type: string
      example:
        email: "test@example.com"
        password: "password"
        name: "John"
        surname: "Doe"
    OperationResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: "User created successfully"
    ExceptionResponse:
      type: object
      properties:
        error:
          type: string
      example:
        error:
          - "Resource not found"
          - "Bad request"
          - "Unauthorized"
          - "Forbidden"
          - "Server error"


